In [ ]:
# 1: Getting Dataset
# 2: Imporing liberaries
# 3: Imporing Dataset
# 4: Finding missing values
# 5: Encoding catagorical data
# 6: Splitting dataset into training and test set
# 7: Feature scaling

#### 2 importing liberaries

In [5]:
import numpy as np
import pandas as pd

#### 3 importing dataset

In [30]:
dataset = pd.DataFrame([
    ['France',44.0, 72000.0, "No"],
    ['Spain',27.0, 45000.0, "Yes"],
    ['Germany',30.0, 54000.0, "No"],
    ['Spain',38.0, 61000.0, "No"],
    ['Germany',40.0, np.nan, "Yes"],
    ['France',35.0, 58000.0, "Yes"],
    ['Spain', np.nan, 52000.0, "No"],
    ['France',48.0, 79000.0, "Yes"],
    ['Germany',50.0, 83000.0, "No"],
    ['France',37.0, 67000.0, "Yes"],
],
                       columns=["Country","Age","Salary","Purchased"]
                       )

dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  45000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Country, Age and Salary are independent that stored the values in x variable

Purchased is dependent that stored its value in y variable


In [45]:
x = dataset[["Country","Age","Salary"]].values

In [46]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [47]:
y = dataset["Purchased"].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

##### 4 filling the missing values in dataset  with sklearn

In [48]:
from sklearn.impute import SimpleImputer

In [49]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

In [54]:
imputer = imputer.fit(x[:,1:3])

In [62]:
x[:,1:3]= imputer.transform(x[:,1:3])

In [63]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63444.444444444445],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

#### 5 encoding catagorical data

In [ ]:
x  # country are catagorical data so convert into encoding (numbers) -> lable to encod

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63444.444444444445],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
label_encoder_x = LabelEncoder()

In [71]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [72]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 45000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63444.444444444445],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
# dummy encoder because it hase more than 2 types of values

from sklearn.preprocessing import OneHotEncoder


In [74]:
onehotencoder = OneHotEncoder()

In [81]:
x= onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [82]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
y # purchased is catagorical data so convert into encoding (numbers) -> lable to encod

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [84]:
from sklearn.preprocessing import LabelEncoder

In [85]:
label_encoder_y = LabelEncoder()

In [89]:
y= label_encoder_y.fit_transform(y)  # y is 1D array

In [90]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

#### 6 split dataset into training and testing set

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [95]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [97]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [98]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [99]:
y_test

array([0, 0], dtype=int64)

#### 7: feature scalling

In [ ]:
# it is using to set the range of values between 0 to 1
from sklearn.preprocessing import StandardScaler

In [101]:
sc_x = StandardScaler()

In [102]:
x_train = sc_x.fit_transform(x_train)

In [ ]:
x_test = sc_x.transform(x_test)

In [103]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [104]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])